[[redirects]]
  from = "/url-list"
  to = "/url-list.html"
  status = 200

[[redirects]]
  from = "/url-admin"
  to = "/url-admin.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect"
  status = 200
  
  [[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[functions]
  directory = "functions"
