[build]
  functions = "functions"
  publish = "."

[[redirects]]
  from = "/url-admin"
  to = "/url-admin.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect"
  status = 200
